export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  SIGNUP_REQUEST: "/signup-request",
  FORGOT_PASSWORD: "/forgotPassword",
  CHANGE_PASSWORD: "/changePassword",
  RESET_PASSWORD: "/resetPassword/:token",
  PASSWORD_CHANGED: "/passwordChanged",
  ABOUT: "/about",
  TESTIMONIAL: "/testimonial",
  MEMBERSHIP: "/membership",
  CLIENT_MEMBERSHIP: "/client-membership",
  DASHBOARD: {
    MAINTAINER: "/maintainer-dashboard",
    ADMIN: "/admin-dashboard",
    TRAINER: "/trainer-dashboard",
    MEMBER: "/member-dashboard",
  },
  EQUIPMENTS: "/equipments",
  MAINTAINERS: "/maintainers",
  TRAINERS: "/trainers",
  CLIENTS: "/clients",
  WORKOUT_PLAN_REQUESTS: "/workoutPlanRequests",
  WORKOUT_PLAN: {
    BASE: "/workoutPlan",
    TRAINER: "/workoutPlan",
    CREATE: "/workoutPlan/:id/create",
    MEMBER: "/workoutPlan/member",
  },
  NOTICES: "/notices",
  SETTINGS: "/settings",
  UNAUTHORIZED: "/unauthorized",
};
