export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgotPassword",
  CHANGE_PASSWORD: "/changePassword",
  RESET_PASSWORD: "/resetPassword/:token",
  PASSWORD_CHANGED: "/passwordChanged",
  ABOUT: "/about",
  TESTIMONIAL: "/testimonial",
  MEMBERSHIP: "/membership",
  DASHBOARD: "/dashboard",
  EQUIPMENTS: "/equipments",
  NOTICES: "/notices",
  SETTINGS: "/settings",
};
