export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgotPassword",
  CHANGE_PASSWORD: "/changePassword",
  RESET_PASSWORD: "/resetPassword/:token",
  PASSWORD_CHANGED: "/passwordChanged",
  ABOUT: "/about",
  TESTIMONIAL: "/testimonial",
  MEMBERSHIP: "/membership",
  DASHBOARD: {
    MAINTAINER: "/maintainer-dashboard",
    ADMIN: "/admin-dashboard",
    TRAINER: "/trainer-dashboard",
  },
  CLIENT_WORKOUT_PLAN: "/clientWorkoutPlan",
  EQUIPMENTS: "/equipments",
  MAINTAINERS: "/maintainers",
  WORKOUT_PLAN_REQUESTS: "/workoutPlanRequests",
  WORKOUT_PLAN: { BASE: "/workoutPlan", CREATE: "/workoutPlan/:id/create" },
  NOTICES: "/notices",
  SETTINGS: "/settings",
  UNAUTHORIZED: "/unauthorized",
};
